apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Name }}-test
spec:
  selector:
    app: {{ .Release.Name }}-devopsfun
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
